<?php

// Apartmenttype
define('IMMOCASTER_LANG_APARTMENTTYPE_',false);
define('IMMOCASTER_LANG_APARTMENTTYPE_NO_INFORMATION',false);
define('IMMOCASTER_LANG_APARTMENTTYPE_ROOF_STOREY',__('Roof storey',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_LOFT',__('Loft',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_MAISONETTE',__('Maisonette',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_PENTHOUSE',__('Penthouse',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_TERRACED_FLAT',__('Terraced flat',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_GROUND_FLOOR',__('Ground floor',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_APARTMENT',__('Apartment',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_RAISED_GROUND_FLOOR',__('Raised ground floor',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_HALF_BASEMENT',__('Half basement',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_APARTMENTTYPE_OTHER',__('Other',IMMOCASTER_PO_TEXTDOMAIN));

// Pets allowed
define('IMMOCASTER_LANG_PETSALLOWED_NO_',false);
define('IMMOCASTER_LANG_PETSALLOWED_0',false);
define('IMMOCASTER_LANG_PETSALLOWED_NO_INFORMATION',false);
define('IMMOCASTER_LANG_PETSALLOWED_NEGOTIABLE',__('By appointment',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_PETSALLOWED_YES',__('Yes',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_PETSALLOWED_NO',__('No',IMMOCASTER_PO_TEXTDOMAIN));

// Objectinfos
define('IMMOCASTER_LANG_OBJECT_INFOHEADLINE_DESC',__('Description',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_OBJECT_INFOHEADLINE_FURNISHING',__('Furnishing',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_OBJECT_INFOHEADLINE_LOCATION',__('Location',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_OBJECT_INFOHEADLINE_OTHER',__('Other',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_OBJECT_INFOHEADLINE_CONTACT',__('Contact',IMMOCASTER_PO_TEXTDOMAIN));

// Flooringtypes
define('IMMOCASTER_LANG_FLOORINGTYPE_NO_INFORMATION',__('No information',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_CONCRETE',__('Concrete',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_EPOXY_RESIN',__('Epoxyresin',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_TILES',__('Tiles',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_PLANKS',__('Planks',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_LAMINATE',__('Laminate',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_PARQUET',__('Parquet',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_PVC',__('PVC',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_CARPET',__('Carpet',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_ANTISTATIC_FLOOR',__('Antistatic floor',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_OFFICE_CARPET',__('Office carpet',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_STONE',__('Stone',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_CUSTOMIZABLE',__('Customizable',IMMOCASTER_PO_TEXTDOMAIN));
define('IMMOCASTER_LANG_FLOORINGTYPE_WITHOUT',__('Without',IMMOCASTER_PO_TEXTDOMAIN));